on: push

jobs:
    test-linux:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Build
              run: cmake -S . -B build && cmake --build build -j 12
        
            - name: Test
              run: cd build/ && ctest