on: push

jobs:
    test-linux:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Install cppcheck
              run: sudo apt-get install cppcheck
            
            - name: Linter
              # run: cppcheck --suppressions-list=cppcheck_suppressions.txt --enable=all -i build .
              run: cppcheck -i build .

            - name: Build
              run: cmake -S . -B build && cmake --build build -j 12
        
            - name: Test
              run: cd build/ && ctest